apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 2
  strategy:
    blueGreen:
      activeService: go-simple-webserver-active
      previewService: go-simple-webserver-preview
      autoPromotionEnabled: false  # set to true for automatic promotion
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/andreia-oca/go-simple-webserver:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: go-simple-webserver-active
spec:
  selector:
    app: go-simple-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: go-simple-webserver-preview
spec:
  selector:
    app: go-simple-webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

